main(){
       #define TAM 51
       int i=0,aux;
       char v[TAM],p,pres[TAM],vt;
       printf("Entre com o verbo regular. ATENCAO: ponto(.) termina a palavra!\n");
       scanf("%c",&p);
       while(p!='.'){
                     v[i]=p;
                     i++;
                     scanf("%c",&p);
                     }
       aux=i-2;
       for(i=0;i<aux;i++)
                         pres[i]=v[i];
       vt=v[aux];
       printf("\n\nPRESENTE\n\n");/*Presente*/
       printf("Eu\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("o\n");
       printf("Tu\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       if(vt=='i')
                  printf("es\n");
       else
           printf("%cs\n",vt);
       printf("Ele\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       if(vt=='i')
                  printf("e\n");
       else
           printf("%c\n",vt);
       printf("Nos\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cmos\n",vt);
       printf("Vos\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       if(vt=='i')
                  printf("is\n");
       else
           printf("%cis\n",vt);
       printf("Eles\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       if(vt=='i')
                  printf("em\n");
       else
           printf("%cm\n\n",vt);
       printf("\n\nPRETERITO PERFEITO\n\n");/*Pretérito Perfeito*/
       printf("Eu\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       if(vt=='a')
                  printf("ei\n");
       else
           printf("i\n");
       printf("Tu\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cste\n",vt);
       printf("Ele\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       if(vt=='a')
                  printf("ou\n",vt);
       else
           printf("%cu\n",vt);
       printf("Nos\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cmos\n",vt);
       printf("Vos\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cstes\n",vt);
       printf("Eles\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cram\n\n",vt);
       printf("\n\nFUTURO DO PRESENTE\n\n");/*Futuro do Presente*/
       printf("Eu\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%crei\n",vt);
       printf("Tu\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cras\n",vt);
       printf("Ele\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cra\n",vt);
       printf("Nós\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%cremos\n",vt);
       printf("Vós\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%creis\n",vt);
       printf("Eles\t");
       for(i=0;i<aux;i++)
                         printf("%c",pres[i]);
       printf("%crao\n\n",vt);
       system("pause");
       }
       
       
